mykino/urls.py
from django.urls import path
from . import views
from .views import filer_movie, search

urlpatterns = [
    path('', views.MovieView.as_view(), name=''),
    path("filter/", filer_movie, name='filter'),
    path("search/", search, name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name="movie_detail"),

    path('review/<int:pk>/', views.AddReview.as_view(), name="add_review"),
    path('actor/<str:slug>/', views.ActorView.as_view(), name="actor_detail"),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("mykino.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mykino/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

from django.urls import reverse


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Аниме"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    treyler = models.URLField("Трейлер", blank=True, null=True)
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Примьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0,
                                         help_text="указывать сумму в долларах")
    fess_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    url = models.SlugField(max_length=130, unique=True)
    reyting = models.DecimalField("Рейтинг КиноПоиска", default=0.0, decimal_places=1, max_digits=2)
    premium = models.BooleanField("Премиум", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из аниме"
        verbose_name_plural = "Кадры из аниме"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь")
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField("Сообщение", max_length=5000)
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

mykino/forms.py
from django import forms
from .models import Reviews, RatingStar, Rating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("text",)

class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

mykino/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from django.views.generic.base import View
from .forms import ReviewForm, RatingForm
from .models import Movie, Genre, Actor, Rating
import requests
from bs4 import BeautifulSoup


class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(premium=False).values("year")

    # def parsingpage(self):
    #     DOLLAR_BYN = "https://www.google.com/search?q=%D0%BA%D1%83%D1%80%D1%81%D1%8B+%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80%D0%B0+%D0%BA+%D0%B1%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC%D1%83+%D1%80%D1%83%D0%B1%D0%BB%D1%8E&oq=%D0%BA%D1%83%D1%80%D1%81%D1%8B+%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80%D0%B0+%D0%BA&aqs=chrome.3.69i57j0i512l9.13088j1j1&sourceid=chrome&ie=UTF-8"
    #     headerss = {
    #         "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}
    #     full_page = requests.get(DOLLAR_BYN, headerss)
    #     soup = BeautifulSoup(full_page.content, "html.parser")
    #     convert = soup.findAll("span", {"class": "DFlfde", "class": "SwHCTb", "data-precision": 2})
    #     cours = convert[0].text
    #     return cours

class MovieView(GenreYear, ListView):

    model = Movie
    queryset = Movie.objects.filter(premium = False)
    template_name = "movies/movie_list.html"
    paginate_by = 6

class MovieDetailView(GenreYear, DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = "url"
    template_name = "movies/movie_detail.html"
    # def get (self, request, slug):
    #     movie = Movie.objects.get(url=slug)
    #     return render(request, "movies/movie_detail.html", {"movie": movie})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context

class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = Movie.objects.get(id=pk)
            form.user = request.user
            form.save()
        return redirect(Movie.objects.get(id=pk).get_absolute_url())

class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = "movies/actor.html"
    slug_field = "name"


def filer_movie(request):
    queryset = Movie.objects.filter(
        Q(year__in=request.GET.getlist("year")) |
        Q(genres__in=request.GET.getlist("genre"))
    )
    return render(request, "movies/movie_list.html", {'movie_list': queryset})

class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie.id = request.POST.get("movie")
            form.user = request.user
            form.save()
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

# class Search(ListView):
#     """Поиск фильмов"""
#     paginate_by = 3
#
#     def get_queryset(self):
#         return Movie.objects.filter(title__icontains=self.request.GET.get("q"))
#
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args, **kwargs)
#         context["q"] = f'q={self.request.GET.get("q")}&'
#         return context

def search(request, *args, **kwargs):
    context =Movie.objects.filter(title__icontains=request.GET.get("q"))
    return render(request, "movies/movie_list.html", {'movie_list': context})

mykino/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}

mykino/templates/movies/base.html
{% extends "base.html" %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent"
         style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
    <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
            <div class="side-bar col-lg-3">
                {% endblock sidebar %}
                {% include "include/side_bar.html" %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
    </div>
    </section>
{% endblock content %}

mykino/templates/movies/movie_detail.html
{% extends "movies/base.html" %}
{% block title %} {{ movie.title }} {% endblock title %}
 {% block container %}
    <div class="container py-md-3">
        {% endblock container %}
                    {% block sidebar %}
            <div class="side-bar col-lg-4">
                {% endblock sidebar %}
                    {% block movie %}
<div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{ movie.title }}
                            </h3>
                            <h5 class="editContent"></h5>
                            <ul>
                                <li style="list-style: none">
                                    <span><b>Год:</b> {{ movie.year }}</span></li>
                                <li style="list-style: none">
                                    <span><b>Страна:</b> {{ movie.country }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Слоган:</b> {{ movie.tagline }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                            <a href="{% url "actor_detail" director.name %}">
                                        {{ director.name }}
                                        </a>
                                        {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>Жанр:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>

                                <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                                </li>
                                <li style="list-style: none"><span><b>Рейтинг Кинопоиск:</b> {{ movie.reyting }}</span>
                                </li>

                                </div>
                                    <div class="clearfix"></div>
                                </div>
                            <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            О фильме {{ movie.title }}
                        </h3>
                        <p>
                            {% for image in movie.movieshots_set.all %}
                            <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.description }}">
                            {% endfor %}
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit;">
                            {{ movie.description }}
                        </p>
                        <p class="mt-3 italic-blue editContent"
                           style="outline: none; cursor: inherit;">
                            <iframe width="560" height="315"
                                    src={{ movie.treyler }}
                                    frameborder="0" allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>

                            </iframe>
                        </p>
                    </div>
                        </div>
                    </div>

                    <hr>
    {% if user.is_authenticated %}
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить
                                    отзыв</h3>
                                <form action="{% url "add_review" movie.id %}" method="post" class="mt-4">
                                    {% csrf_token %}
                                    <div class="form-group editContent">
                                        <label for="contactcomment" class="editContent">Ваш
                                            комментарий
                                            *</label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <div class="d-sm-flex">
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3">Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                    </div>
{% else %}
    <a>Оставлять комментарии могут только зарегистрированные пользователи</a>
    <a href="{% url 'account_login' %}">
                            Вход
                        </a>
    {% endif %}
                        <div class="single-form-left">
                            {% for review in movie.reviews_set.all %}
                                <div class="media-body mt-4">
                                    <h5 class="mt-0 editContent">
                                        {{ review.user }}
                                    </h5>
                                    <p class="mt-2 editContent">
                                        {{ review.text }}
                                    </p>
                                </div>
                            {% endfor %}
                        </div>


                </div>

 {% endblock movie %}

mykino/templates/movies/movie_list.html
{% extends "movies/base.html" %}
{% block header%} bg1 {% endblock header%}
                    {% block movie %}
                    <div class="left-ads-display col-lg-9">
                        <div class="row">
                            {% for movie in movie_list %}
                            <div class="col-md-4 product-men">
                                <div class="product-shoe-info editContent text-center mt-lg-4" >
                                    <div class="men-thumb-item">
                                        <img src="{{movie.poster.url}}" class="img-fluid" class="img-deals" alt="" >
                                    </div>
                                    <div class="item-info-product">
                                        <h4 class="">
                                            <a href="{{ movie.get_absolute_url }}" class="editContent" >
                                                {{ movie.title }}
                                            </a>
                                        </h4>

                                        <div class="product_price">
                                            <div class="grid-price">
                                                <span class="money editContent" >{{movie.tagline}}</span>
                                            </div>
                                        </div>
<!--                                        <ul class="stars">-->
<!--                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>-->
<!--                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>-->
<!--                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>-->
<!--                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>-->
<!--                                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>-->
<!--                                        </ul>-->
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="grid-img-right mt-4 text-right bg bg1" >
                            {% include 'include/pagination.html' %}
                        </div>
                    </div>

{% endblock movie %}
